fix: fix type errors caused by unsuccessful queries
myparcelnl/prestashop pull request #135
Opened 2022-04-06 09:18 UTC by EdieLemoine

2022-04-07 08:41 UTC, joerivanveen requested changes

2022-04-07 08:41 UTC, joerivanveen commented on src/Factory/Consignment/ConsignmentFactory.php
> +        $this->orderData         = $orderData;
```suggestion
        $this->orderData         = OrderLabel::getDataForLabelsCreate([$order->getId()])[0];
```

2022-04-07 14:39 UTC, markernst97 submitted a review, later dismissed

2022-04-11 14:58 UTC, joerivanveen approved these changes, later dismissed

2022-04-11 15:08 UTC, markernst97 approved these changes, later dismissed

2022-04-12 12:32 UTC, EdieLemoine commented
/rebase

2022-04-12 14:14 UTC, joerivanveen requested changes

2022-04-12 14:14 UTC, joerivanveen commented on src/Factory/Consignment/ConsignmentFactory.php
>              return substr($labelDescription, 0, 42) . '...';
```suggestion
            return substr($labelDescription, 0, Constant::ORDER_DESCRIPTION_MAX_LENGTH - 3) . '...';
```

2022-04-20 09:18 UTC, markernst97 submitted a review, later dismissed

2022-04-21 07:32 UTC, joerivanveen approved these changes, later dismissed

2022-04-21 14:35 UTC, joerivanveen approved these changes

2022-04-22 08:41 UTC, markernst97 approved these changes

2022-04-22 08:43 UTC, merged