fix: distribute weight over multiple labels
myparcelnl/prestashop pull request #145
Opened 2022-04-20 11:28 UTC by markernst97

2022-04-20 12:05 UTC, EdieLemoine commented
dit is een feature!

2022-04-20 12:07 UTC, EdieLemoine requested changes

2022-04-20 12:07 UTC, EdieLemoine commented on src/Factory/Consignment/ConsignmentFactory.php
> +        for ($i = 0; $i < $labelAmount; ++$i) {
```suggestion
        for ($i = 0; $i < $labelAmount; $i++) {
```

2022-04-20 12:07 UTC, EdieLemoine commented on src/Factory/Consignment/ConsignmentFactory.php
> +        $this->validateWeight($distributedWeight);
kan dit niet ook in een validator? eentje die door order->shipments loopt en dan kijkt of alles goed is?

2022-04-21 14:37 UTC, joerivanveen approved these changes

2022-04-26 07:55 UTC, RichardPerdaan approved these changes

2022-04-28 08:52 UTC, EdieLemoine approved these changes

2022-05-10 14:45 UTC, merged