fix: accomodate deleted customer
myparcelnl/prestashop pull request #147
Opened 2022-04-21 13:56 UTC by joerivanveen

Resolves #143

2022-04-21 14:15 UTC, markernst97 submitted a review, later dismissed

2022-04-21 14:39 UTC, EdieLemoine requested changes

2022-04-21 14:39 UTC, EdieLemoine commented on src/Model/OrderLabel.php
> +                if (! $result[0]['email']) {
Kan het nog voorkomen dat dit een error gooit? misschien `?? false` voor de zekerheid?

2022-04-21 14:39 UTC, EdieLemoine commented on src/Model/OrderLabel.php
> +                return $result[0];
Dit returnde eerst `$result`, klopt dit zo wel?

2022-04-21 14:54 UTC, joerivanveen commented on src/Model/OrderLabel.php
> +                return $result[0];
Ja, het moet juist de eerste row returnen (als het goed is is er natuurljk maar 1 row), niet de array met rows, daar ging de export verderop op fout, want die verwacht gewoon de gegevens in een array (dus de eerste row als zodanig).

2022-04-21 14:55 UTC, joerivanveen commented on src/Model/OrderLabel.php
> +                if (! $result[0]['email']) {
Scherp

2022-04-22 15:21 UTC, EdieLemoine approved these changes

2022-04-26 08:39 UTC, markernst97 approved these changes

2022-04-26 12:37 UTC, merged