feat: allow insurance from nl to be
myparcelnl/prestashop pull request #150
Opened 2022-04-28 16:57 UTC by joerivanveen

2022-05-16 14:21 UTC, EdieLemoine requested changes
De hotfix moet er ook nog uit...

2022-05-16 14:21 UTC, EdieLemoine commented on views/js/admin/src/components/common/form/PackageTypeSelectFormGroup.vue
> +      options: ctx.attrs.options,
dit kan(/mag) niet, dit moet een prop worden

2022-05-16 14:21 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +
kun je hier op z'n minst een comment zetten die uitlegt waarom we niks doen met deze error?

2022-05-16 14:21 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +            $hasInsurance = '0' !== $postValues['deliveryOptions']['shipmentOptions']['insurance'];
uitlijnen

2022-05-16 14:21 UTC, EdieLemoine commented on src/Service/WeightService.php
> +    public static function convertWeightToGrams($orderWeight): int
👀

2022-05-18 08:44 UTC, markernst97 submitted a review, later dismissed

2022-05-19 09:53 UTC, EdieLemoine requested changes

2022-05-19 09:53 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +                !== $postValues['deliveryOptions']['shipmentOptions']['insurance']);
ok dit is wel heel lelijk, doe er dan maar een enter tussen

2022-05-19 10:20 UTC, EdieLemoine submitted a review, later dismissed

2022-05-23 07:27 UTC, EdieLemoine approved these changes

2022-05-23 11:05 UTC, markernst97 approved these changes

2022-05-23 11:06 UTC, merged