build: use pdk weightservice
myparcelnl/prestashop pull request #158
Opened 2022-05-25 13:59 UTC by joerivanveen

2022-05-27 08:10 UTC, EdieLemoine requested changes

2022-05-27 08:10 UTC, EdieLemoine commented on src/OrderSettings/OrderSettings.php
> +            $this->orderWeight = WeightService::convertToGrams($this->order->getTotalWeight(), strtolower(Configuration::get('PS_WEIGHT_UNIT')));
1. Waarom doe je hier strtolower en op andere plekken niet? 
3. Misschien is het voor dit soort gevallen wel oke (of zelfs "mooi") om de PDK class in je plugin te extenden met zoiets, zodat die parameter overal consistent is.

```php
class WeightService extends \MyParcelNL\Pdk\Service\WeightService {
	public static convertToGrams($amount) {
    return parent::convertToGrams($amount, Configuration::get('PS_WEIGHT_UNIT'));
  }
}
```

2022-06-09 13:53 UTC, EdieLemoine submitted a review, later dismissed

2022-06-09 14:00 UTC, Mark-Ernst submitted a review, later dismissed

2022-06-14 15:51 UTC, EdieLemoine approved these changes, later dismissed

2022-06-15 07:32 UTC, Mark-Ernst submitted a review, later dismissed

2022-06-17 08:49 UTC, EdieLemoine approved these changes

2022-06-17 11:24 UTC, Mark-Ernst approved these changes

2022-06-17 11:48 UTC, merged