feat: add real multicollo
myparcelnl/prestashop pull request #166
Opened 2022-06-15 07:48 UTC by wthijmen

2022-06-15 07:49 UTC, Mark-Ernst submitted a review, later dismissed

2022-06-15 08:52 UTC, EdieLemoine requested changes
Dit ziet er niet uit als een `feature`

2022-06-15 08:54 UTC, EdieLemoine requested changes

2022-06-15 08:54 UTC, EdieLemoine commented on src/Factory/Consignment/ConsignmentFactory.php
> +                CarrierPostNL::NAME === $carrierName
Dit is weer business logic herhalen, kijk eens hoe ver je komt met `$consignment->canHaveExtraOption()`?

2022-06-16 06:56 UTC, Mark-Ernst submitted a review, later dismissed

2022-06-16 12:56 UTC, joerivanveen submitted a review, later dismissed

2022-06-20 15:19 UTC, Mark-Ernst submitted a review, later dismissed

2022-06-21 13:01 UTC, joerivanveen submitted a review, later dismissed
Zie evt. opmerking, maar ik heb t idee dat je branches toch nog niet helemaal lekker gescheiden zijn...

2022-06-21 13:01 UTC, joerivanveen commented on src/Factory/Consignment/ConsignmentFactory.php
> +        $this->orderData   = OrderLabel::getDataForLabelsCreate($order->getId());
Uitlijning? Maar deze zag ik in je andere pr ook staan. Hmmm...

2022-06-21 14:43 UTC, EdieLemoine submitted a review, later dismissed

2022-06-30 09:57 UTC, joerivanveen approved these changes

2022-06-30 12:03 UTC, EdieLemoine commented
denk ff wat beter na over die titels

2022-07-01 07:42 UTC, Mark-Ernst approved these changes

2022-07-01 07:46 UTC, merged