refactor: edit label description
myparcelnl/prestashop pull request #168
Opened 2022-06-16 09:18 UTC by wthijmen

2022-06-16 12:59 UTC, joerivanveen requested changes

2022-06-16 12:59 UTC, joerivanveen commented on src/Module/Configuration/Form/LabelForm.php
> +                    $this->module->l(sprintf($labelDescription, Constant::ORDER_DESCRIPTION_MAX_LENGTH), 'labelform'),
De vertaalfuncties kunnen alleen maar strings lezen, dus je moet die vertaalfunctie aanroepen bij het toewijzen van de $labelDescription (L16) en dan de sprintf toepassen op _de al vertaalde_ string.

2022-06-21 12:57 UTC, joerivanveen requested changes

2022-06-21 12:57 UTC, joerivanveen commented on src/Module/Configuration/Form/LabelForm.php
> +        $translate = $this->module->l('The maximum length is %d characters. You can add the following variables to the description');
Uitlijnen =jes

2022-06-21 12:57 UTC, joerivanveen commented on src/Factory/Consignment/ConsignmentFactory.php
> +        $this->orderData   = OrderLabel::getDataForLabelsCreate($order->getId());
Uitlijning =jes

2022-06-21 12:57 UTC, joerivanveen commented on src/Factory/Consignment/ConsignmentFactory.php
>          $distributedWeight = $consignment->getTotalWeight() / $labelAmount;
Uitlijning = t.o.v. de =jes hierboven, of een witregel ertussen, zodat het er in ieder geval netjes uit ziet

2022-06-21 12:57 UTC, joerivanveen commented on src/Factory/Consignment/ConsignmentFactory.php
> +            $orderIso       = $countryService->getShippingCountryIso2($order);
Je hebt de $orderIso niet aangepast, terwijl je toch wel een nieuwe commit moest maken. Zou je een betere naam kunnen gebruiken? Tenzij je echt vindt dat $orderIso een duidelijke naam is, maar als ik dat los lees als variabele naam, heb ik niet een scherp idee wat daarmee bedoeld zou kunnen worden. En wel bij $shippingCountryIso2 bv, of andere opties wellicht.

2022-06-21 13:41 UTC, Mark-Ernst approved these changes, later dismissed

2022-06-21 14:03 UTC, joerivanveen approved these changes, later dismissed

2022-06-21 14:03 UTC, joerivanveen commented on src/Factory/Consignment/ConsignmentFactory.php
>          return $collection;
Voor elke return hoort een witregel, ter info

2022-06-24 10:04 UTC, joerivanveen approved these changes

2022-06-24 10:16 UTC, Mark-Ernst approved these changes

2022-06-24 10:33 UTC, merged