feat: option concept shipments
myparcelnl/prestashop pull request #174
Opened 2022-06-30 07:32 UTC by wthijmen

2022-07-01 07:49 UTC, joerivanveen requested changes

2022-07-01 07:49 UTC, joerivanveen commented on src/Factory/Consignment/ConsignmentFactory.php
> +        return Configuration::get(Constant::PROCESS_SHIPMENT_INSTANTLY);
De constante is nu het tegenovergestelde (in tekst) van de werking ervan, dat is verwarrend... Ik zou die constante ook iets met CONCEPT_FIRST noemen

2022-07-01 07:49 UTC, joerivanveen commented on src/Model/OrderLabel.php
> +        if (! \Gett\MyparcelBE\Factory\Consignment\ConsignmentFactory::isConceptFirstConfiguration()) {
Import class

2022-07-03 12:04 UTC, joerivanveen requested changes

2022-07-03 12:04 UTC, joerivanveen commented on src/Service/AdminOrderService.php
> +            $collection = $collection->createConcepts();
Waarom deze toewijzing? Nu is het een MyParcelCollection, terwijl het een ConsignmentCollection was (MyParcelCollection extends weliswaar ConsignmentCollection, dus de return value van deze method is nog ok), maar ik zie niet waarom je dit doet, het lijkt mij verwarrend.

2022-07-03 12:04 UTC, joerivanveen commented on src/Service/AdminOrderService.php
>          OrderLogger::addLog([
Wanneer je dit bestand aanpast, zou ik graag in de log ook zien of hij de labels heeft gemaakt of de concepten.

2022-07-04 14:42 UTC, joerivanveen requested changes
zie de twee suggesties betr. witregels, verder ziet het er volgens mij goed uit!

2022-07-04 14:42 UTC, joerivanveen commented on src/Service/AdminOrderService.php
> +            return 'consignments';
```suggestion
            
            return 'consignments';
```

2022-07-04 14:42 UTC, joerivanveen commented on src/Service/AdminOrderService.php
> +        return 'concepts';
```suggestion
        
        return 'concepts';
```

2022-07-04 14:44 UTC, joerivanveen approved these changes, later dismissed

2022-07-05 06:37 UTC, Mark-Ernst approved these changes, later dismissed

2022-07-05 14:17 UTC, EdieLemoine requested changes

2022-07-05 14:17 UTC, EdieLemoine commented on src/Module/Configuration/Form/GeneralForm.php
> +                'label'    => $this->module->l('Turn on concept shipment before exporting', $this->getNamespace()),
Kan dit logischer? Dit zegt mij al niet zo veel, laat staan een gebruiker

2022-07-05 14:17 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +     * @param $collection
type

2022-07-05 14:17 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +    private function exportLabelOrCreateConcept($collection): string
type

2022-07-05 14:17 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +     * @param $consignment
type

2022-07-05 14:17 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +    private function addToOrderLabels($consignment): object
type

2022-07-05 14:17 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +                'order'   => $orderLabel->id_order,
hele order meegeven aan de orderlogger

2022-07-05 14:17 UTC, EdieLemoine commented on views/js/admin/src/components/order-list-column/LabelCard.vue
> +        @click="() => print(label) & refresh(label)">
Maak hier maar gewoon een method van waarin je dit netjes in 2 regels doet ipv deze creepy syntax

2022-07-05 14:17 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +
enter

2022-07-05 14:17 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +            $orderLabels[] = $this->addToOrderLabels($consignment);
`add` wat? als je dingen refactort op zo'n manier moet de functienaam ook wel echt goed omschrijven wat er gebeurt

2022-07-05 14:17 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +        $typeTextForLog = $this->exportLabelOrCreateConcept($collection);
Dit liever inline, of anders de log statement in die functie zelf. Op deze manier is het heel gek, door dit in een tekst variabele te stoppen impliceer je dat er niks gebeurt in de functie. Functies die meerdere dingen doen zijn onduidelijk, die functie doet nu al "shipment of concept aanmaken" maar ook nog eens "melden of er een shipment of een concept aangemaakt is/wordt".

2022-07-05 15:08 UTC, EdieLemoine requested changes

2022-07-05 15:08 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +        if (! ConsignmentFactory::isConceptFirstConfiguration()) {
geen negated conditions, deze moet je flippen

2022-07-05 15:08 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +        $factory        = new ConsignmentFactory($postValues);
uitlijnen

2022-07-05 15:08 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +
enter te veel

2022-07-05 15:08 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +
hier ook

2022-07-05 15:08 UTC, EdieLemoine commented on views/js/admin/src/components/order-list-column/LabelCard.vue
> +        await execute(LabelAction.REFRESH, label);
waarom doe je eigenlijk print en dan refresh? dat kost dubbel zoveel tijd als printen ook een refresh laten uitvoeren

2022-07-05 15:08 UTC, EdieLemoine commented on views/js/admin/src/components/order-list-column/LabelCard.vue
>        print: async(label: ShipmentLabel): Promise<void> => execute(LabelAction.PRINT, label),
wordt deze nog gebruikt?

2022-07-05 15:08 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +            'message' => sprintf('Creating consignments: %s', $collection->toJson()),
geen info meer over of het een concept is geworden of niet?

2022-07-07 09:29 UTC, joerivanveen submitted a review, later dismissed

2022-07-07 11:06 UTC, Mark-Ernst submitted a review, later dismissed

2022-07-11 12:17 UTC, joerivanveen submitted a review, later dismissed

2022-07-13 14:10 UTC, Mark-Ernst approved these changes, later dismissed

2022-07-13 14:25 UTC, EdieLemoine requested changes

2022-07-13 14:25 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +        } else {
kan gewoon ternary

2022-07-13 14:25 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +    private function consignmentToOrderLabel(object $consignment): object
object??? dit kan niet in php 7.1, zorg dat je editor goed staat. Plus dit moet geen object zijn maar gewoon een AbstractConsignment

2022-07-13 14:25 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +     * @return object $orderLabel
Dit is geen "object", dit is een OrderLabel

2022-07-13 14:50 UTC, Mark-Ernst approved these changes, later dismissed

2022-07-13 15:00 UTC, EdieLemoine approved these changes

2022-07-13 15:12 UTC, Mark-Ernst approved these changes

2022-07-14 07:30 UTC, joerivanveen approved these changes

2022-07-14 12:44 UTC, merged