fix: checkout uses specifically set myparcelconfig
myparcelnl/prestashop pull request #175
Opened 2022-06-30 15:24 UTC by joerivanveen

2022-06-30 16:33 UTC, wthijmen requested changes

2022-06-30 16:33 UTC, wthijmen commented on src/Service/DeliveryOptionsConfigProvider.php
> +            throw new RuntimeException("Carrier {$this->psCarrierId} not found ");
Single quotes

2022-07-01 07:45 UTC, wthijmen approved these changes, later dismissed

2022-07-01 10:55 UTC, Mark-Ernst approved these changes, later dismissed

2022-07-05 10:11 UTC, EdieLemoine requested changes

2022-07-05 10:11 UTC, EdieLemoine commented on src/Service/DeliveryOptionsConfigProvider.php
>       * @var int[]
```suggestion
     * @var string
```

2022-07-05 10:24 UTC, EdieLemoine approved these changes

2022-07-05 13:04 UTC, wthijmen approved these changes

2022-07-05 13:09 UTC, merged