fix: returns
myparcelnl/prestashop pull request #176
Opened 2022-07-11 13:49 UTC by Mark-Ernst

2022-07-13 13:05 UTC, wthijmen requested changes

2022-07-13 13:05 UTC, wthijmen commented on views/js/admin/src/services/actions/executeAdminAction.ts
> +    if (!await waitForReturnsFormModalClose(modalData)) {
Spatie bij !

2022-07-13 13:05 UTC, wthijmen commented on src/Service/AdminOrderService.php
> +            ->setConsignmentId((int) $orderLabel->id_label)
Spatie voor object operator & meerdere check Codacy.

2022-07-13 14:29 UTC, EdieLemoine requested changes

2022-07-13 14:29 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +        $largeFormat     = $postValues['largeFormat'] === '2';
Magic string!

2022-07-13 14:29 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +            ->setPerson($address->firstname . ' ' . $address->lastname)
concatenation vervangen door iets beters

2022-07-13 14:29 UTC, EdieLemoine commented on views/js/admin/src/components/forms/ReturnsForm.vue
> +    const packageTypeMailbox: SelectOption = {
waarom zit dit er hard coded in? deze data is er al vanuit de backend

2022-07-13 14:29 UTC, EdieLemoine commented on views/js/admin/src/components/forms/ReturnsForm.vue
> +    const packageFormatLarge = 2;
dit mag hier ook niet in

2022-07-14 12:51 UTC, EdieLemoine commented
/rebase

2022-07-15 13:23 UTC, wthijmen submitted a review, later dismissed

2022-07-18 07:34 UTC, EdieLemoine requested changes

2022-07-18 07:34 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +    private const PACKAGE_FORMAT_LARGE = 2;
? `Constant::PACKAGE_FORMAT_LARGE`

2022-07-18 07:34 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +        $largeFormat     = (int) $postValues['largeFormat'] === self::PACKAGE_FORMAT_LARGE;
yoda

2022-07-18 07:34 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +        $largeFormat     = (int) $postValues['largeFormat'] === self::PACKAGE_FORMAT_LARGE;
ik denk ook dat het duidelijker is als je dit ding pas naar `int` cast wanneer je `setLargeFormat` doet, zeker omdat presta dit ook behandelt alsof het een cijfer is terwijl het eigenlijk een ja/nee is

2022-07-18 07:34 UTC, EdieLemoine commented on src/Module/Carrier/CarrierOptionsCalculator.php
> +    public function getAvailablePackageTypeNames(bool $idToName = true, string $prefix = null): array
geen parameter gebruiken, check zelf of items numeriek zijn

2022-07-18 13:05 UTC, wthijmen approved these changes

2022-07-18 14:24 UTC, EdieLemoine approved these changes

2022-07-18 14:24 UTC, merged