Fix/empty variables abstractconsignment
myparcelnl/prestashop pull request #178
Opened 2022-07-13 07:34 UTC by wthijmen

Needs myparcelnl/sdk#7.4.1

2022-07-13 09:30 UTC, Mark-Ernst approved these changes, later dismissed

2022-07-13 14:26 UTC, EdieLemoine requested changes

2022-07-13 14:26 UTC, EdieLemoine commented on src/Constant.php
> +    public const REQUIRED_LABEL_KEYS = [
formatting

2022-07-13 14:26 UTC, EdieLemoine commented on src/Model/OrderLabel.php
> +                if ($emptyFields) {
entertje hier

2022-07-13 14:26 UTC, EdieLemoine commented on src/Model/OrderLabel.php
> +                            'Customer information in the following fields are missing: %s',
Waarom niet gewoon zo?
```suggestion
                            'The following fields are missing but required: %s',
```

2022-07-13 14:54 UTC, Mark-Ernst approved these changes

2022-07-14 09:40 UTC, EdieLemoine approved these changes

2022-07-14 10:56 UTC, joerivanveen approved these changes

2022-07-14 12:43 UTC, merged