fix: deliveryoptions carrier from admin orderview
myparcelnl/prestashop pull request #179
Opened 2022-07-14 12:18 UTC by wthijmen

2022-07-14 14:58 UTC, Mark-Ernst submitted a review, later dismissed

2022-07-15 07:00 UTC, joerivanveen submitted a review, later dismissed

2022-07-15 07:16 UTC, EdieLemoine requested changes

2022-07-15 07:16 UTC, EdieLemoine commented on src/Module/Hooks/AdminPanelRenderService.php
> +            $context['deliveryOptions']['carrierName'] = $context['deliveryOptions']['carrier'];
uitlijnen

2022-07-15 07:16 UTC, EdieLemoine commented on views/js/admin/types/contexts.d.ts
> +  carrier: null | number;
```suggestion
  carrierId: null | number;
```

2022-07-15 07:16 UTC, EdieLemoine commented on views/js/admin/src/data/eventBus/DeliveryOptionsEventBus.ts
> +    carrier: number | null,
```suggestion
    carrierId: number | null,
```

2022-07-15 07:16 UTC, EdieLemoine commented on src/Module/Hooks/AdminPanelRenderService.php
> +            $context['deliveryOptions']['carrier']     = $order->getIdCarrier();
zeker als je ook name gebruikt moet dit id heten.

```suggestion
            $context['deliveryOptions']['carrierId']     = $order->getIdCarrier();
```

2022-07-15 08:50 UTC, closed without merging