ci: update rebase workflow
myparcelnl/prestashop pull request #185
Opened 2022-08-04 10:29 UTC by joerivanveen

2022-08-04 10:33 UTC, EdieLemoine requested changes

2022-08-04 10:33 UTC, EdieLemoine commented on .github/workflows/release.yml
>      uses: myparcelnl/prestashop/.github/workflows/rebase.yml@main
hier kan je tegenwoordig een lokaal pad gebruiken :) dus je kunt dit doen: `./.github/workflows/rebase.yml`

dit zou anders nooit je changes gebruiken omdat dit nu altijd naar main verwijst

2022-08-04 10:33 UTC, EdieLemoine commented on .github/workflows/release.yml
> +      force: true
dit zou ik nog even weglaten, ik heb het er als "test" bij woo in gezet, om te kijken of het werkt en niks sloopt

2022-08-04 11:03 UTC, wthijmen submitted a review, later dismissed

2022-08-08 12:10 UTC, EdieLemoine requested changes

2022-08-08 12:10 UTC, EdieLemoine commented on .github/workflows/release.yml
> +    uses: ./.github/workflows/rebase.yml@main
geen branch
```suggestion
    uses: ./.github/workflows/rebase.yml
```

2022-08-08 12:11 UTC, EdieLemoine approved these changes

2022-08-08 12:14 UTC, wthijmen approved these changes

2022-08-08 12:24 UTC, merged