fix: correct package type at export
myparcelnl/prestashop pull request #187
Opened 2022-08-23 14:58 UTC by wthijmen

Resolves #186

2022-08-23 14:59 UTC, Mark-Ernst submitted a review, later dismissed

2022-08-24 07:21 UTC, EdieLemoine requested changes

2022-08-24 07:21 UTC, EdieLemoine commented on views/js/admin/src/components/forms/ShipmentOptionsForm.vue
> +      v-model="packageType"
packageTypeId wordt nu nergens meer gebruikt

2022-08-24 07:30 UTC, EdieLemoine approved these changes

2022-08-24 07:32 UTC, Mark-Ernst approved these changes

2022-08-25 14:42 UTC, merged