fix(modal): show package options
myparcelnl/prestashop pull request #200
Opened 2022-11-14 15:48 UTC by joerivanveen

2022-11-15 16:01 UTC, wthijmen approved these changes, later dismissed

2022-11-18 16:30 UTC, EdieLemoine requested changes

2022-11-18 16:30 UTC, EdieLemoine commented on src/Factory/Consignment/ConsignmentFactory.php
> +        if (isset($this->request[Constant::LABEL_CHECK_ONLY]) && $this->request[Constant::LABEL_CHECK_ONLY]) {
```suggestion
        if ($this->request[Constant::LABEL_CHECK_ONLY]) ?? false) && $this->request[Constant::LABEL_CHECK_ONLY]) {
```

2022-11-18 16:30 UTC, EdieLemoine commented on src/Factory/Consignment/ConsignmentFactory.php
> +        $requiredKeys      = $this->request[Constant::LABEL_CHECK_ONLY] ?? false ? [] : Constant::REQUIRED_LABEL_KEYS;
```suggestion
        $requiredKeys      = ($this->request[Constant::LABEL_CHECK_ONLY] ?? false) ? [] : Constant::REQUIRED_LABEL_KEYS;
```

2022-11-18 16:30 UTC, EdieLemoine approved these changes, later dismissed

2022-11-21 08:04 UTC, wthijmen approved these changes, later dismissed

2022-11-25 08:10 UTC, wthijmen approved these changes

2022-11-25 12:49 UTC, Mark-Ernst approved these changes

2022-11-25 13:01 UTC, merged