fix(return shipments): distinguish labels correctly
myparcelnl/prestashop pull request #201
Opened 2022-11-17 16:55 UTC by joerivanveen

2022-11-18 12:03 UTC, EdieLemoine requested changes

2022-11-18 12:03 UTC, EdieLemoine commented on src/Constant.php
>          self::PACKAGE_TYPE_PACKAGE       => 'package',
kun je niet gewoon de consts uit abstractconsignment gebruiken?

2022-11-18 12:03 UTC, EdieLemoine commented on src/Module/Upgrade/Upgrade1_7_2.php
> +        } catch (\Throwable $e) {
moet dit niet gerapporteerd worden?

2022-11-18 12:03 UTC, EdieLemoine commented on src/Service/AdminOrderService.php
> +        //$consignment                 = $collection->where('status', '!=', null)->first();
comment?

2022-11-18 16:33 UTC, EdieLemoine submitted a review, later dismissed

2022-11-21 08:03 UTC, wthijmen submitted a review, later dismissed

2022-11-21 08:03 UTC, wthijmen commented on src/Provider/OrderLabelProvider.php
> +                if ("1" === $label['is_return']) {
Quotes

2022-11-21 08:13 UTC, wthijmen approved these changes, later dismissed

2022-11-24 12:12 UTC, wthijmen submitted a review, later dismissed

2022-11-24 12:13 UTC, Mark-Ernst approved these changes, later dismissed

2022-11-25 08:32 UTC, wthijmen approved these changes

2022-11-25 12:50 UTC, Mark-Ernst approved these changes

2022-11-25 13:01 UTC, merged