fix: fix actions on cards and modals
myparcelnl/prestashop pull request #208
Opened 2022-12-19 14:54 UTC by Mark-Ernst

2022-12-22 08:39 UTC, joerivanveen requested changes

2022-12-22 08:39 UTC, joerivanveen commented on src/Provider/OrderLabelProvider.php
> +                if (array_key_exists('is_return', $label) && '1' === $label['is_return']) {
Ik zou isset doen, want array_key_exists is veel duurder en als de waarde NULL is dan moet ie toch false geven.

2022-12-22 08:39 UTC, joerivanveen commented on views/js/admin/src/services/actions/onNewLabels.ts
> +    case LabelAction.PRINT:
Waarom is de volgorde veranderd? Hij is nu niet meer alfabetisch, en het lijkt functioneel niet uit te maken hier.

2022-12-22 08:39 UTC, joerivanveen commented on views/js/admin/src/components/common/form/SelectFormGroup.vue
> +const {model, props, setup} = useSelectModel();
Het maakt mij persoonlijk niet heel veel uit, maar bij een aantal van deze constructies zijn de omringende spaties verwijderd, en bij een aantal niet. Ik vind het mooier met spaties. Maar als de linter zegt dat het zonder moet, dan verwacht ik dat het overal waar het aangeraakt is zonder spaties is.

2022-12-29 10:44 UTC, joerivanveen approved these changes

2022-12-29 13:52 UTC, wthijmen approved these changes

2023-01-05 09:56 UTC, merged