fix(orders): export correct recipient name
myparcelnl/prestashop pull request #277
Opened 2024-10-09 11:54 UTC by EdieLemoine

Needs #276

2024-10-11 13:30 UTC, FreekVR approved these changes
Functioneel geen aanmerkingen, zie alleen 2x kleine codestyle feedback van Codacy die wel netjes zijn om nog op te lossen.

Ook nog een tweetal failures in de testsuite - mismatch tussen integer en boolean return value / expectations

2024-10-11 13:32 UTC, FreekVR requested changes, later dismissed
Functioneel geen aanmerkingen, zie alleen 2x kleine codestyle feedback van Codacy die wel netjes zijn om nog op te lossen.

Ook nog een tweetal failures in de testsuite - mismatch tussen integer en boolean return value / expectations

2024-10-25 07:46 UTC, FlorianSDV approved these changes

2024-10-30 08:43 UTC, FreekVR approved these changes

2024-11-13 13:20 UTC, merged