fix: dpz weight classes automatically selected and retained
myparcelnl/prestashop pull request #53
Opened 2021-10-26 14:53 UTC by joerivanveen

2021-10-28 07:43 UTC, EdieLemoine requested changes
wat een UNIT

2021-10-28 07:43 UTC, EdieLemoine commented on src/Constant.php
> +    public const PACKAGE_TYPES                                          = [ // TODO remove this
todo?

2021-10-28 07:43 UTC, EdieLemoine commented on src/DeliverySettings/DeliverySettings.php
> +    public static function setExtraOptionsForOrder(ExtraOptions $extraOptions, OrderCore $order): void
phpdocjes missen

2021-10-28 07:43 UTC, EdieLemoine commented on src/DeliverySettings/DeliverySettingsRepository.php
> +    private function __construct()
__construct en __clone kunnen weg toch?

2021-10-28 07:43 UTC, EdieLemoine commented on src/DeliverySettings/DeliverySettingsRepository.php
> +    $order): void
rare indenting

2021-10-28 07:43 UTC, EdieLemoine commented on src/DeliverySettings/DeliverySettingsRepository.php
> +    public static function getInstance(): DeliverySettingsRepository
Maak anders meteen even die handige trait hiervan 👼🏼

2021-10-28 07:43 UTC, EdieLemoine commented on src/DeliverySettings/DeliverySettingsRepository.php
> +        foreach (self::$deliverySettingsByCartId as $cartId => $deliverySettings) {
kan dit niet in 1 query?

2021-10-28 07:43 UTC, EdieLemoine commented on src/DeliverySettings/ExtraOptions.php
> +    private $labelAmount;
phpdocs

2021-10-28 07:43 UTC, EdieLemoine commented on src/DeliverySettings/ExtraOptions.php
> +    public function __construct(array $extraOptions = [])
phpdoc

2021-10-28 07:43 UTC, EdieLemoine commented on src/Label/LabelOptionsResolver.php
> +    private function getOnlyToRecipient(array $delivery_settings, array $products, int $id_carrier)
je mag hier best even wat formatten en missende phpdocs genereren 👼🏼

2021-10-28 12:22 UTC, joerivanveen commented on src/Constant.php
> +    public const PACKAGE_TYPES                                          = [ // TODO remove this
weggehaald

2021-10-28 12:23 UTC, joerivanveen commented on src/DeliverySettings/DeliverySettings.php
> +    public static function setExtraOptionsForOrder(ExtraOptions $extraOptions, OrderCore $order): void
return void hoefde niet toch?

2021-10-28 12:26 UTC, joerivanveen commented on src/DeliverySettings/DeliverySettingsRepository.php
> +    private function __construct()
ze zitten daar zodat je geen instance ervan maakt, als het goed is maak je dat ook nooit dus dan kunnen ze weg, ik zie ze inderdaad ook verder nergens als zodanig, dus ik haal ze weg. Enige is dan dat je de class dus wel kunt instantieren, maar dat moet je dan gewoon niet doen :-)

2021-10-28 12:27 UTC, joerivanveen commented on src/DeliverySettings/DeliverySettingsRepository.php
> +    $order): void
idd, gefixt

2021-10-28 12:34 UTC, joerivanveen commented on src/DeliverySettings/DeliverySettingsRepository.php
> +        foreach (self::$deliverySettingsByCartId as $cartId => $deliverySettings) {
volgens mij niet zo makkelijk omdat het insert of update is, per id. en omdat er doorgaans maar 1 in zal zitten heeft het ook niet zoveel impact, dacht ik.

2021-10-28 12:37 UTC, joerivanveen commented on src/DeliverySettings/ExtraOptions.php
> +    public function __construct(array $extraOptions = [])
ok

2021-10-28 12:37 UTC, joerivanveen commented on src/DeliverySettings/ExtraOptions.php
> +    private $labelAmount;
ok

2021-10-28 12:45 UTC, joerivanveen commented on src/Label/LabelOptionsResolver.php
> +    private function getOnlyToRecipient(array $delivery_settings, array $products, int $id_carrier)
ok

2021-10-28 13:12 UTC, joerivanveen commented on src/DeliverySettings/DeliverySettingsRepository.php
> +    public static function getInstance(): DeliverySettingsRepository
werkt niet omdat de getInstance method in die trait private is, oplossing: public maken, of code herschrijven zodat die getInstance private kan blijven, maar ik ben bang dat het dan een wrapper wordt, en dat is ook stom, advies?

2021-11-01 13:58 UTC, RichardPerdaan approved these changes, later dismissed

2021-11-01 13:59 UTC, EdieLemoine commented on src/DeliverySettings/DeliverySettings.php
> +    public static function setExtraOptionsForOrder(ExtraOptions $extraOptions, OrderCore $order): void
wel met 400 params

2021-11-01 14:00 UTC, EdieLemoine commented on src/DeliverySettings/DeliverySettingsRepository.php
> +    public static function getInstance(): DeliverySettingsRepository
Gewoon public maken toch?

2021-11-01 17:29 UTC, RichardPerdaan approved these changes, later dismissed

2021-11-02 08:51 UTC, EdieLemoine approved these changes, later dismissed

2021-11-02 11:08 UTC, RichardPerdaan approved these changes, later dismissed

2021-11-02 11:19 UTC, EdieLemoine submitted a review, later dismissed

2021-11-04 09:28 UTC, RichardPerdaan approved these changes

2021-11-04 09:32 UTC, EdieLemoine approved these changes

2021-11-04 09:34 UTC, merged