fix: status change during export for statuses that have timing issues…
myparcelnl/prestashop pull request #75
Opened 2021-11-16 14:29 UTC by joerivanveen

… with webhooks

2021-11-17 12:27 UTC, EdieLemoine requested changes

2021-11-17 12:27 UTC, EdieLemoine commented on controllers/admin/AdminMyParcelBELabelController.php
> +            ApiLogger::addLog(printf('Could not set status for shipment %s', $labelId));
moet `sprintf` zijn

2021-11-17 12:27 UTC, EdieLemoine commented on src/Model/Webhook/StatusChangeWebhookPayload.php
> +        1, 2, 12, 14
indenten, en constanten van maken?

2021-11-19 07:58 UTC, RichardPerdaan approved these changes

2021-11-22 08:45 UTC, EdieLemoine approved these changes

2021-11-24 12:27 UTC, merged